/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ReceiptSuccessRate

class App {

    static void main(String[] args) {
        App app = new App()
        app.startProgram()
    }

    void startProgram(){
        String filePath = "C:/Users/Andrius/Desktop"
        RateCalculator rateCalculator = new RateCalculator()
        rateCalculator.calculateRate(filePath)
    }

}
